FROM node:20-slim

RUN apt-get update \
 && apt-get install -y openjdk-17-jre-headless \
 && npm install -g firebase-tools@latest

WORKDIR /workspace

COPY firebase.json ./
COPY .firebaserc ./
COPY start-emulators.sh ./
RUN chmod +x start-emulators.sh

ENTRYPOINT ["./start-emulators.sh"]
