# One bridge network so containers talk via service name.
networks:
  finnet:

#  FIRESTORE EMULATOR     #
services:
  emulators:
    build:
      context: .
      dockerfile: Dockerfile.emu   # see step 2
    working_dir: /workspace
    volumes:
      - ./:/workspace              # mounts firebase.json here
      - ./firebase-data:/workspace/firebase-data
    command: |
      firebase emulators:start
      --project finflow-local
      --only auth,firestore,database,ui
      --import=./seed-data    
      --export-on-exit=./seed-data
    ports:
      - "9099:9099"    # Auth emulator
      - "8080:8080"    # Firestore emulator
      - "9000:9000"    # RTDB emulator
      - "4000:4000"    # UI web
      - "9150:9150"    # UI websocket
    networks: [finnet]

#  FinGPT API (GPU)
  fingpt-api:
    build:
      context: ./Projects/fingpt_service
      args:
        FIRESTORE_EMULATOR_HOST: firestore-emulators:8080
    runtime: nvidia              # <-- enable GPU in Docker Desktop
    environment:
      - FIRESTORE_EMULATOR_HOST=firestore-emulators:8080
      # optional PyTorch VRAM tune-ups
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:128
    ports:
      - "8081:8080"
    depends_on:
      - emulators 
    networks: [finnet]


#  Prophet ETL batch       #

  fin-etl:
    build:
      context: ./Projects/fin_etl
      args:
        FIRESTORE_EMULATOR_HOST: firestore-emulator:8080
    environment:
      - FIRESTORE_EMULATOR_HOST=firestore-emulator:8080
    depends_on: [emulators]
    networks: [finnet]
    # Run once then exit; leave it commented if you’ll trigger via cron
    command: python etl_prophet.py
